### ISSUE TITLE
How do i use this plugin in cordova?

### ISSUE THREAD

**Issue by astutesoftware** [SeVeNDuS/cordova-plugin-fyber#1]
I tried adding the plugin via
cordova plugin add https://github.com/SeVeNDuS/cordova-plugin-fyber.git

then
xx = new FyberPlugin();    
xx.initialize('24180', '789', '########', 'T$')

but it claims there is no object as FyberPlugin

**Comment by astutesoftware** [comment]
i got thru by doing
xx = Fyber;
            
            xx.initialize('xxx', 'xxxx', 'xxx', 'T$',fyber_success, fyber_error);
now on invoking initialize i get an error
"Attempt to invoke virtual method 'boolean.org.json.JSONObject.has(java.lang.String)' on a null object reference.

**Comment by SeVeNDuS** [comment]
Hi,

I am using this plugin in a production app and I use in this way

Fyber.initialize({ appKey: 'XXXX', userId: userid, securityToken: 'xxxxxxxx', virtualCurrencyName: 'conins'});
        $a.on(Futmondo.Helpers.Utils.getClickEvent(), function () {
            Fyber.showOfferwall();
        });

the problem is that you are sending parameters as arguments instead of an object
Regards

**Comment by astutesoftware** [comment]
Oh yes. worked now. Thanks a lot.
